import type { CatalogShape } from "../catalog";
import { enAdmin } from "../en/admin";

const ja: Record<string, string> = {
  "Profile": "プロフィール", "Manage your account details, avatar, and security.": "アカウント情報、アバター、セキュリティを管理します。", "Loading profile…": "プロフィールを読み込んでいます…",
  "Avatar": "アバター", "Click the avatar to upload a new photo": "アバターをクリックして新しい写真をアップロード",
  "Display name": "表示名", "Enter display name": "表示名を入力", "Save display name": "表示名を保存", "Edit display name": "表示名を編集", "User ID": "ユーザー ID", "Copy user ID": "ユーザー ID をコピー",
  "Security": "セキュリティ", "Current password": "現在のパスワード", "Enter current password": "現在のパスワードを入力", "New password": "新しいパスワード", "Enter new password": "新しいパスワードを入力", "Must be at least 8 characters": "8 文字以上で入力してください", "Confirm new password": "新しいパスワード（確認）", "Changing…": "変更中…", "Change password": "パスワードを変更", "Show password": "パスワードを表示", "Hide password": "パスワードを隠す",
  "Failed to load user information": "ユーザー情報を読み込めませんでした", "Display name cannot be empty": "表示名を空にすることはできません", "Display name updated": "表示名を更新しました", "Failed to update display name": "表示名を更新できませんでした", "User ID copied": "ユーザー ID をコピーしました", "Failed to copy": "コピーできませんでした", "Please select an image file": "画像ファイルを選択してください", "Avatar updated": "アバターを更新しました", "Failed to upload avatar": "アバターをアップロードできませんでした", "Password changed successfully": "パスワードを変更しました", "Failed to change password": "パスワードを変更できませんでした", "Password must be at least 8 characters": "パスワードは 8 文字以上で入力してください", "Passwords do not match": "パスワードが一致しません",
  "Admin": "管理", "Deployment-wide settings. Changes apply to all users on their next connection.": "デプロイ全体の設定です。変更は各ユーザーの次回接続時に適用されます。", "You don't have access to this page.": "このページへのアクセス権がありません。", "Loading admin settings…": "管理設定を読み込んでいます…", "Something went wrong loading admin settings.": "管理設定の読み込み中に問題が発生しました。",
  "General": "一般", "Gatekeepers": "ゲートキーパー", "Formats": "フォーマット", "Access": "アクセス", "Allow new sign-ups": "新規登録を許可", "When disabled, only existing users can sign in.": "無効にすると、既存のユーザーのみサインインできます。", "Site name": "サイト名", "Logo": "ロゴ", "Upload logo": "ロゴをアップロード", "Change logo": "ロゴを変更", "Restore default logo": "既定のロゴに戻す", "Theme": "テーマ", "Default": "既定", "Blue": "青", "Green": "緑", "Purple": "紫", "Pink": "ピンク", "Teal": "ティール", "Custom": "カスタム", "Banner": "バナー", "Type": "種類", "Neutral": "ニュートラル", "Info": "情報", "Success": "成功", "Warning": "警告", "Danger": "危険", "Brand": "ブランド", "Top-bar notice": "トップバーのお知らせ", "Agent instructions": "エージェントへの指示", "{{count}} / {{max}} characters": "{{count}} / {{max}} 文字", "Save": "保存", "Reset": "リセット", "Restore default": "既定に戻す",
  "Choose which connections users can add and what resources they can access.": "ユーザーが追加できる接続とアクセス可能なリソースを選択します。", "Configure connector credentials": "コネクター認証情報を設定", "Disabled": "無効", "Optional": "任意", "Enabled": "有効", "Off for everyone": "全員に対してオフ", "Users can add it themselves": "ユーザーが自分で追加可能", "On for everyone automatically": "全員に自動でオン", "Off": "オフ", "Too long by {{count}} characters": "{{count}} 文字超過しています",
  "Update failed": "更新できませんでした", "Announcement saved": "お知らせを保存しました", "Failed to save announcement": "お知らせを保存できませんでした", "Banner saved": "バナーを保存しました", "Failed to save banner": "バナーを保存できませんでした", "Accent color saved": "アクセントカラーを保存しました", "Failed to save accent color": "アクセントカラーを保存できませんでした", "Site name saved": "サイト名を保存しました", "Failed to save site name": "サイト名を保存できませんでした", "Logo saved": "ロゴを保存しました", "Failed to save logo": "ロゴを保存できませんでした", "Default logo restored": "既定のロゴに戻しました", "Failed to remove logo": "ロゴを削除できませんでした", "System prompt instructions saved": "システムプロンプトの指示を保存しました", "Failed to save instructions": "指示を保存できませんでした",
  "Connector configuration": "コネクター設定", "Configure deployment settings used when users connect their accounts.": "ユーザーがアカウントを接続するときに使用するデプロイ設定を構成します。", "Back to Admin": "管理に戻る", "Loading connector configurations…": "コネクター設定を読み込んでいます…", "Something went wrong loading connector configurations.": "コネクター設定の読み込み中に問題が発生しました。", "Connector configuration management is not enabled for this deployment. Configuration is read-only.": "このデプロイではコネクター設定の管理が有効になっていません。設定は読み取り専用です。", "No credentialed connectors are installed on this deployment.": "このデプロイには認証情報が必要なコネクターがインストールされていません。", "Configured": "設定済み", "Needs setup": "設定が必要", "Callback URL": "コールバック URL", "Ask an administrator to configure this connector.": "管理者にこのコネクターの設定を依頼してください。", "Follow the provider setup guide, register the callback URL above, then enter the credentials.": "プロバイダーのセットアップガイドに従って上記のコールバック URL を登録し、認証情報を入力してください。", "Follow the setup guide, then enter the connector settings.": "セットアップガイドに従って、コネクター設定を入力してください。", "View setup guide": "セットアップガイドを見る", "Update configuration": "設定を更新", "Save configuration": "設定を保存", "Failed to save connector configuration": "コネクター設定を保存できませんでした", "{{name}} configuration saved. It may take a moment to become available.": "{{name}} の設定を保存しました。利用可能になるまで少し時間がかかる場合があります。", "{{name}} configuration saved, but status could not be refreshed. Reload this page to check availability.": "{{name}} の設定を保存しましたが、状態を更新できませんでした。このページを再読み込みして利用可能か確認してください。",
  "Add AI Model": "AI モデルを追加", "Add Model": "モデルを追加", "AI model added successfully": "AI モデルを追加しました", "Failed to add model": "AI モデルを追加できませんでした", "Other {{provider}}…": "その他の {{provider}}…", "Select Provider": "プロバイダーを選択", "Select Model": "モデルを選択", "Choose a provider…": "プロバイダーを選択…", "Choose an AI model…": "AI モデルを選択…", "Model ID": "モデル ID", "The model identifier as specified by the provider (e.g., '{{model}}')": "プロバイダーが指定するモデル識別子（例: '{{model}}'）", "Display Name": "表示名", "Human-readable name shown in the UI": "UI に表示する分かりやすい名前", "Cloudflare Account ID": "Cloudflare アカウント ID", "The Cloudflare account to bill for Workers AI usage": "Workers AI の利用料金を請求する Cloudflare アカウント", "API Token": "API トークン", "Optional for local Ollama access": "ローカルの Ollama へのアクセスでは任意", "Your {{provider}} API token for billing": "請求に使用する {{provider}} API トークン", "API URL": "API URL", "URL of your Ollama server": "Ollama サーバーの URL", "Advanced Settings": "詳細設定", "Please select a provider": "プロバイダーを選択してください", "Please select a model": "モデルを選択してください", "Please enter the model ID": "モデル ID を入力してください", "Please enter a display name": "表示名を入力してください", "Please enter your API token": "API トークンを入力してください", "Please enter your Cloudflare account ID": "Cloudflare アカウント ID を入力してください", "Please enter the Ollama API URL": "Ollama API URL を入力してください",
  "Blueprint": "ブループリント", "Blueprints": "ブループリント", "No description": "説明なし", "Screenshot of {{title}}": "{{title}} のスクリーンショット", "Open blueprint {{title}}": "ブループリント「{{title}}」を開く", "AI Model": "AI モデル", "Agent": "エージェント", "No agent": "エージェントなし", "Untitled blueprint": "無題のブループリント", "Search blueprints…": "ブループリントを検索…", "Try again": "再試行", "Explore": "探索", "Discover featured blueprints and start building.": "注目のブループリントを見つけて作成を始めましょう。", "Failed to load featured blueprints": "注目のブループリントを読み込めませんでした", "No blueprints match": "一致するブループリントはありません", "No featured blueprints yet": "注目のブループリントはまだありません", "Try a different search term.": "別の検索語をお試しください。", "Open featured blueprint {{title}}": "注目のブループリント「{{title}}」を開く", "Reusable starting points from your workspaces.": "ワークスペースから作成した再利用可能な出発点です。", "Upload": "アップロード", "Uploading…": "アップロード中…", "Upload a .gadget archive": ".gadget アーカイブをアップロード", "Blueprint uploaded": "ブループリントをアップロードしました", "Failed to upload blueprint": "ブループリントをアップロードできませんでした", "Something went wrong loading your blueprints.": "ブループリントの読み込み中に問題が発生しました。", "No blueprints found": "ブループリントが見つかりません", "No blueprints yet": "ブループリントはまだありません", "Favorite": "お気に入りに追加", "Unfavorite": "お気に入りから削除", "Failed to update favorite": "お気に入りを更新できませんでした", "Removed from library": "ライブラリから削除しました", "Failed to remove blueprint": "ブループリントを削除できませんでした",
  "Create blueprint": "ブループリントを作成", "Edit blueprint": "ブループリントを編集", "Turn this gadget into a reusable starting point.": "このガジェットを再利用可能な出発点にします。", "Title": "タイトル", "Blueprint title": "ブループリントのタイトル", "Description (optional)": "説明（任意）", "Blueprint description": "ブループリントの説明", "Change": "変更", "Processing…": "処理中…", "Create": "作成", "Creating…": "作成中…", "Saving…": "保存中…", "Loading…": "読み込み中…", "Close": "閉じる", "Blueprint screenshot preview": "ブループリントのスクリーンショットプレビュー", "Blueprint created.": "ブループリントを作成しました。", "Blueprint updated.": "ブループリントを更新しました。", "Blueprint deleted.": "ブループリントを削除しました。", "Failed to load blueprints": "ブループリントを読み込めませんでした", "Could not load connections.": "接続を読み込めませんでした。", "Please select an image file.": "画像ファイルを選択してください。", "Failed to process screenshot": "スクリーンショットを処理できませんでした", "Delete": "削除", "Deleting…": "削除中…", "Copied": "コピーしました", "Copy failed": "コピーに失敗しました", "Copy link": "リンクをコピー",
  "Loading blueprint…": "ブループリントを読み込んでいます…", "Blueprint not found": "ブループリントが見つかりません", "This blueprint may have been removed or the link may be incorrect.": "このブループリントは削除されたか、リンクが正しくない可能性があります。", "Couldn’t load blueprint": "ブループリントを読み込めませんでした", "Back to Explore": "探索に戻る", "Log in to create a gadget": "ログインしてガジェットを作成", "Configure {{count}} remaining connections": "残り {{count}} 件の接続を設定", "Configure connections": "接続を設定", "Create Gadget": "ガジェットを作成", "Add to library": "ライブラリに追加", "Download archive": "アーカイブをダウンロード", "Downloading…": "ダウンロード中…", "Updating…": "更新中…", "Remove from library": "ライブラリから削除", "Removing…": "削除中…", "Feature blueprint": "注目に設定", "Unfeature blueprint": "注目から解除", "Ready": "準備完了", "Suggested": "候補", "Configure": "設定", "For spawned agents only": "生成されたエージェント専用", "Close screenshot": "スクリーンショットを閉じる",
  "App": "アプリ", "Apps": "アプリ", "Start with": "ここから開始", "New {{noun}}": "新しい{{noun}}", "Couldn't create a new {{noun}}": "新しい{{noun}}を作成できませんでした", "Standard formats": "標準フォーマット", "Choose the blueprints offered as standard output formats.": "標準の出力フォーマットとして提供するブループリントを選択します。", "Couldn't update standard formats": "標準フォーマットを更新できませんでした", "Produces {{plural}}": "{{plural}}を生成", "No declared format. You’ll name it.": "宣言されたフォーマットがありません。名前を付けてください。", "No standard formats yet": "標準フォーマットはまだありません", "Bundled": "同梱", "Needs a name": "名前が必要", "Move up": "上へ移動", "Move down": "下へ移動", "How it’s presented": "表示方法", "Name": "名前", "Plural": "複数形", "How the agent picks it": "エージェントによる選択方法", "Hint": "ヒント", "Choose icon": "アイコンを選択",
  "Cloudflare account": "Cloudflare アカウント", "Loading accounts…": "アカウントを読み込んでいます…", "No eligible accounts are available on this connection.": "この接続で利用できる対象アカウントはありません。", "Failed to reconnect Cloudflare": "Cloudflare に再接続できませんでした", "Failed to select account": "アカウントを選択できませんでした", "Cloudflare account selected": "Cloudflare アカウントを選択しました", "unknown": "不明", "Usage & billing": "使用状況と請求", "Loading usage…": "使用状況を読み込んでいます…", "User-funded usage": "ユーザー負担の利用", "A funded Cloudflare account is required for all AI inference.": "すべての AI 推論には残高のある Cloudflare アカウントが必要です。", "Free daily allowance": "1 日の無料利用枠", "{{remaining}} of {{limit}} requests remaining today": "本日は残り {{remaining}} / {{limit}} リクエスト", "Resets at 00:00 UTC, in {{duration}}.": "00:00 UTC（{{duration}}後）にリセットされます。", "Not connected": "未接続", "Connect Cloudflare": "Cloudflare に接続", "Cloudflare connection needs re-authentication": "Cloudflare 接続の再認証が必要です", "Re-authenticate the connected Cloudflare account before AI inference can continue.": "AI 推論を続ける前に接続済みの Cloudflare アカウントを再認証してください。", "Re-authenticate Cloudflare": "Cloudflare を再認証", "Unable to load Cloudflare accounts": "Cloudflare アカウントを読み込めません", "No eligible Cloudflare account": "対象の Cloudflare アカウントがありません", "Choose which Cloudflare account to bill": "請求先の Cloudflare アカウントを選択", "Account balance: {{amount}}": "アカウント残高: {{amount}}", "Add credits": "クレジットを追加", "Learn more about AI Gateway unified billing.": "AI Gateway の統合請求について詳しく見る。", "Choose a Cloudflare account": "Cloudflare アカウントを選択", "Connect a funded account to continue": "残高のあるアカウントを接続して続行", "You've reached your free usage limit": "無料利用枠の上限に達しました", "Maybe later": "後で", "0 seconds": "0 秒", "{{hours}}h {{minutes}}m {{seconds}}s": "{{hours}}時間 {{minutes}}分 {{seconds}}秒", "{{minutes}}m {{seconds}}s": "{{minutes}}分 {{seconds}}秒", "{{seconds}}s": "{{seconds}}秒", "Resets in {{days}}d {{hours}}h": "{{days}}日 {{hours}}時間後にリセット",
  "Some services are temporarily unavailable: {{services}}": "一部のサービスは一時的に利用できません: {{services}}", "Failed to load available services": "利用可能なサービスを読み込めませんでした", "Grant the additional access in the new tab.": "新しいタブで追加アクセスを許可してください。", "Failed to request additional access": "追加アクセスを要求できませんでした", "Opening…": "開いています…", "Connected": "接続済み", "Credentials expired": "認証情報の有効期限切れ", "Grant access": "アクセスを許可", "Reconnect": "再接続", "Connected account": "接続済みアカウント",
  "Add the apps and accounts your workspaces can use. Connect once, then wire them into anything you build.": "ワークスペースで使用するアプリやアカウントを追加します。一度接続すれば、作成したものに組み込めます。", "Something went wrong loading your gatekeepers.": "ゲートキーパーの読み込み中に問題が発生しました。", "Check your connection and try refreshing the page.": "接続を確認してページを再読み込みしてください。", "Loading gatekeepers…": "ゲートキーパーを読み込んでいます…", "Search gatekeepers…": "ゲートキーパーを検索…", "Available": "利用可能", "No gatekeepers match": "一致するゲートキーパーはありません", "No gatekeepers yet": "ゲートキーパーはまだありません", "We couldn't find anything matching your search.": "検索に一致するものが見つかりませんでした。", "Connect Account": "アカウントを接続", "No services available to connect.": "接続できるサービスはありません。", "Add connection": "接続を追加", "Create connection": "接続を作成", "Create New Connection": "新しい接続を作成", "Choose what this gadget should be able to use.": "このガジェットが使用できるものを選択します。", "Search services, apps, data sources…": "サービス、アプリ、データソースを検索…", "Please select an AI model": "AI モデルを選択してください", "Failed to create connection": "接続を作成できませんでした", "Account": "アカウント", "Expired credentials": "期限切れの認証情報", "Additional permission needed": "追加の権限が必要", "Select a model": "モデルを選択", "None (no agent)": "なし（エージェントなし）", "Agent bindings": "エージェントのバインディング", "Nothing is available to offer spawned agents here. Create the agent from a gadget's Connections tab to give it access to that gadget and its resources.": "生成されたエージェントに提供できるものがありません。ガジェットの［接続］タブからエージェントを作成し、そのガジェットとリソースへのアクセスを許可してください。", "Verify your access": "アクセスを確認", "Verify your access again": "アクセスを再確認", "Waiting for connection…": "接続を待っています…", "Connect": "接続", "Using your account": "自分のアカウントを使用", "Waiting for access…": "アクセスを待っています…", "Verify again": "再確認", "Verify and open": "確認して開く", "Loading connections…": "接続を読み込んでいます…", "No matching resources.": "一致するリソースはありません。", "Expired — click to re-authenticate": "有効期限切れ — クリックして再認証", "Connect new account": "新しいアカウントを接続", "Choose an account before selecting a resource.": "リソースを選択する前にアカウントを選択してください。", "Loading configurator…": "設定ツールを読み込んでいます…", "Resources": "リソース", "Resources to enable": "有効にするリソース", "What this gatekeeper can do": "このゲートキーパーでできること", "Disconnecting…": "切断中…", "Yes, disconnect": "はい、切断します", "Adding…": "追加中…",
  "AI providers": "AI プロバイダー", "Configure the AI models available to your workspaces.": "ワークスペースで利用できる AI モデルを設定します。", "Add provider": "プロバイダーを追加", "Search providers…": "プロバイダーを検索…", "built-in": "組み込み", "quick": "クイック", "Quick model. Click to clear": "クイックモデル。クリックして解除", "Click to set as quick model": "クリックしてクイックモデルに設定", "Provider actions": "プロバイダーの操作", "Clear quick model": "クイックモデルを解除", "Set as quick model": "クイックモデルに設定", "Delete provider": "プロバイダーを削除", "Failed to delete provider": "プロバイダーを削除できませんでした", "Failed to update default model": "既定のモデルを更新できませんでした", "Something went wrong loading your providers.": "プロバイダーの読み込み中に問題が発生しました。", "No AI providers yet": "AI プロバイダーはまだありません", "Add a provider to start building workspaces with AI.": "プロバイダーを追加して AI を使ったワークスペースの作成を始めましょう。", "Add your first provider": "最初のプロバイダーを追加", "No providers found": "プロバイダーが見つかりません",
  "Context & Skills": "コンテキストとスキル", "Curated collections of knowledge your agents read, plus reusable skills they can apply.": "エージェントが参照する知識コレクションと、再利用可能なスキルです。", "Context & Skills are coming soon to {{siteName}}": "{{siteName}} にコンテキストとスキルが近日登場", "Collection": "コレクション", "Skill": "スキル", "{{count}} documents": "{{count}} 件のドキュメント", "Reusable skill": "再利用可能なスキル", "Company Handbook": "社内ハンドブック", "Brand Voice & Style": "ブランドボイスとスタイル", "API Reference": "API リファレンス", "Summarize meeting notes": "会議メモを要約", "Sales Playbook": "営業プレイブック", "Draft a customer email": "顧客向けメールを作成", "{{count}}d ago": "{{count}}日前", "{{count}}w ago": "{{count}}週間前",
  "Gatekeeper app": "ゲートキーパーアプリ", "Resource configurator": "リソース設定ツール", "This app is not available on this deployment.": "このアプリはこのデプロイでは利用できません。", "Configurator is no longer available.": "設定ツールは利用できなくなりました。", "Configurator is not ready.": "設定ツールの準備ができていません。", "Configurator did not provide its resource URL. Please try again.": "設定ツールからリソース URL を取得できませんでした。もう一度お試しください。",
};

function localize<T>(value: T): CatalogShape<T> {
  if (typeof value === "string") return (ja[value] ?? value) as CatalogShape<T>;
  const result: Record<string, unknown> = {};
  for (const [key, child] of Object.entries(value as Record<string, unknown>)) result[key] = localize(child);
  return result as CatalogShape<T>;
}

export const jaAdmin = localize(enAdmin);
